services:
  mariadb:
    image: mariadb:12.1
    platform: linux/arm64/v8
    container_name: medtrajet_mariadb
    restart: unless-stopped
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
      MARIADB_DATABASE: "medtrajet"
      MARIADB_USER: "medtrajet-api"
      MARIADB_PASSWORD: "hubnis-biwfiT-0veche"
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: